task 4 Krainev A
alvls/mp1-2020-2 pull request #49
Opened 2020-11-05 22:11 UTC by AlexanderOfficial

Программу реализовал через структуры. Скидка изначально уже есть у каждого товара, вводить ее не нужно.
Созданы отдельные функции для печати каталога, поиска номера продукта в каталоге и для создания структуры 
В процессе работы программы вводятся штрихкоды: для окончания работы(печати чека) нужно ввести 0
Не до конца понял выражение "суммарная скидка". Сделал именно сумарную скидку в процентах, если нужно - исправлю.
При начале работы программы высвечивается каталог товара: для удобства тестировки.
Где выделял динамическую память- потом  освободил.

2020-11-25 09:07 UTC, alvls requested changes

2020-11-25 09:07 UTC, alvls commented on Krainev_AA/task4/Source.c
> +    char* name[100]; //имя товара
Неверное объявление. Указатель тут лишний. Достаточно `char name[100]`.
Далее везде, где вы работаете со строкой, аналогично.

2020-11-25 09:07 UTC, alvls commented on Krainev_AA/task4/Source.c
> +    free(res_st);//очищаю ранее выделенную память
Код после `return` выполнен не будет, поэтому free никогда не произойдет. Утечка памяти.

2020-11-25 09:09 UTC, alvls commented
Александр, замечания по коду см. выше.
Кроме того, нет защиты от ввода неверного кода товара - программа просто падает.
И было бы неплохо зациклить программу. Где вы видели кассовый аппарат, который выключается после каждого покупателя :)?

2020-11-25 15:45 UTC, AlexanderOfficial commented
Согласен, сейчас пришлю исправленное.

2020-11-25 16:37 UTC, AlexanderOfficial commented
Александр Владимирович, внёс изменения:
1. Сделал защиту от неверного ввода штрихкода.SearchProduct теперь возвращает -1 если товар не найден,
а  if((SearchProduct(BARCODE, st))!=(-1)) в main проверяет это и если получает -1, то просит ввести штрихкод заново.
2. С освобождением  free(res_st)  запутался. Сделал так:
при каждом вызове  addProduct происходит очищение res_st перед выделением ей памяти  в res_st = malloc(sizeof(struct product));
А чтобы происходило удаление res_st с последними данными из каталога: очищение проиходит уже в main после каталога.
3.Убрал в некоторых местах лишние указатели.
4. Зациклил работу программы. Поместил весь код в while(1), после строчки printf("До встречи!"); происходит очищение 
экрана для работы со следующим покупателем(system("cls");).

Почему-то не компилируется (ошибка в библиотеке string.h) если запускать в *.sln, но если если создать и скопировать в другой проект,то все работает.

2020-11-25 20:56 UTC, alvls requested changes

2020-11-25 20:56 UTC, alvls commented on Krainev_AA/task4/Source.c
> +    free(res_st);
Так тоже неверно. Очищать память до ее выделения нельзя.
А в вашем случае очистка вообще должна быть в самом конце программы. И очищать нужно через массив st, в который вы сохраняете указатели.

2020-11-25 21:21 UTC, AlexanderOfficial commented on Krainev_AA/task4/Source.c
> +    free(res_st);
Хорошо, сейчас исправлю.

2020-11-25 21:42 UTC, AlexanderOfficial commented
Добавил  free(st); в конец программы.

2020-11-25 21:45 UTC, alvls requested changes

2020-11-25 21:45 UTC, alvls commented on Krainev_AA/task4/Source.c
> +        free(st);
Снова неверно. st - это массив. Его не нужно освобождать. Удалить нужно память, на которую вы настроили указатели в этом массиве. И делать это нужно в цикле.

2020-11-25 22:32 UTC, AlexanderOfficial commented on Krainev_AA/task4/Source.c
> +        free(st);
for (i=0; i<product_counter; i++)
    free(st[i]);
free(st);
Так? 
Но есть еще идея
void cleanFunction(const struct product* st[],product_counter) {
     for (int i=0, i<product_counter,i++){
            free(st[i]->price);
            free(st[i]->name);
            free(st[i]->barcode);
            free(st[i])->sale);
      }
}

2020-11-26 06:57 UTC, alvls commented on Krainev_AA/task4/Source.c
> +        free(st);
так
for (i=0; i<product_counter; i++)
free(st[i]);

2020-11-26 07:30 UTC, AlexanderOfficial commented
Добавил цикл с  free(st[])

2020-12-10 17:35 UTC, AlexanderOfficial commented
Александр Владимирович, передаю  в printAllSort  значение  getCountFromCounter, но не пользуюсь, так как забыл сделать в конце строчку, которая показывала бы сколько файлов было отсортировано(

2020-12-11 07:43 UTC, alvls commented on Krainev_AA/task4/Source.c
> +        }
Удаление памяти нужно вынести из цикла и делать только в конце работы программы, иначе падение при втором запуске.

2020-12-11 07:44 UTC, alvls commented
Задание 4.

Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,7
Качество   проектирования: | 2,0
Качество кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 7,7

2020-12-19 14:56 UTC, alvls commented
Задание 5

Работа принята |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 5,7
Качество   проектирования: | 3,0
Качество   кода: | 3,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 11,7

Снял 0.3 балла за то, что для папок с большим числом файлов (тысячи) невозможно дождаться, пока все файлы будут выведены на экран.

2020-12-29 12:34 UTC, alvls commented
Задание 6

Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 6,0
Качество   проектирования: | 3,0
Качество кода: | 3,0
Бонус: | 0,2
Штраф: | 0,0
__Итого:__ | 12,2

2020-12-29 18:47 UTC, merged