Solution task4 ShushpanovNM
alvls/mp1-2020-2 pull request #52
Opened 2020-11-07 20:16 UTC by n1k1tkooo

2020-11-25 09:57 UTC, alvls requested changes

2020-11-25 09:57 UTC, alvls commented on shushpanov_nm/task4/Source.c
> +char* name[300];
Неверное объявление. Указатель тут лишний. Достаточно `char name[300]`.
Далее везде, где вы работаете со строкой, аналогично.

2020-11-25 09:57 UTC, alvls commented on shushpanov_nm/task4/Source.c
> +    free(massivProductList);
Код после `return` выполнен не будет, поэтому `free` никогда не произойдет. Утечка памяти.

2020-11-25 09:59 UTC, alvls commented
Никита, замечания по коду см. выше.
И было бы неплохо зациклить программу. Где вы видели кассовый аппарат, который выключается после каждого покупателя :)?
Кроме того, в вашем коде есть значительные пересечения с кодом Александра Крайнева. Поясните, кто у кого заимствовал.

2020-11-25 10:00 UTC, n1k1tkooo commented
Взаимствовал я, так как я не успевал и был после операции.

Subarist 

среда, 25 ноября 2020 г., 12:59 +0300 от notifications@github.com  <notifications@github.com>:
>Никита, замечания по коду см. выше.
>И было бы неплохо зациклить программу. Где вы видели кассовый аппарат, который выключается после каждого покупателя :)?
>Кроме того, в вашем коде есть значительные пересечения с кодом Александра Крайнева. Поясните, кто у кого заимствовал.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

2020-12-11 07:37 UTC, alvls commented
Задание 4.

Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,7
Качество   проектирования: | 2,0
Качество кода: | 2,0
Бонус: | 0,0
Штраф: | 1,0
__Итого:__ | 6,7

Я не стал снижать оценку вдвое за заимствование кода, снял только 1 балл. Еще 0.3 балла за то, что вы так и оставили free там, где он не нужен.

2020-12-20 18:06 UTC, alvls commented
Задание 5

Работа принята |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 5,7
Качество   проектирования: | 3,0
Качество   кода: | 3,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 11,7

Снял 0.3 балла за то, что для папок с большим числом файлов (тысячи) на экран выводятся все файлы и приходится очень долго ждать. Вместо этого можно было, например, проверить число файлов и спросить пользователя, нужно ли их выводить.

2020-12-20 18:07 UTC, merged