task4
alvls/mp1-2020-2 pull request #54
Opened 2020-11-08 13:37 UTC by alser3217

2020-11-13 15:22 UTC, alser3217 commented
Заметил, что в список продуктов не входит их стоимость.

2020-11-25 10:28 UTC, alvls requested changes

2020-11-25 10:28 UTC, alvls commented on raschetnov_as/task4/Source.c
> +	printf("\t\t\t\t\t\t\t%d stands for %s\n ", days[6], weekDays[6]);
Почему не циклом?

2020-11-25 10:28 UTC, alvls commented on raschetnov_as/task4/Source.c
> +	printf("\t\t\t\t\t\t\t%d stands for %s\t\t%d$\n", productsArray[10], shopProducts[10], priceArray[10]);
Почему не циклом?

2020-11-25 10:31 UTC, alvls commented
Алексей, замечания по коду см. выше.
Кроме того, было бы неплохо зациклить программу. Где вы видели кассовый аппарат, который выключается после каждого покупателя :)?

2020-11-25 10:46 UTC, alser3217 commented
> Алексей, замечания по коду см. выше.
> Кроме того, было бы неплохо зациклить программу. Где вы видели кассовый аппарат, который выключается после каждого покупателя :)?

2020-11-25 10:50 UTC, alvls commented
Не закрывайте pull request. Просто делайте новые коммиты.

2020-11-25 10:50 UTC, alser3217 commented
Куда-то нажал там выше случайно. Я внесу правки. В коде Вы видимо не заметили, что массив штрих-кодов определён через int, что не соответствует условию задания. Я не вижу принципиальных отличий в работе кода, если определять массив через int и если же это делать через char, зато если это делать через int, то это экономит строки, а пользователю важен только конечный продукт, сомневаюсь что ему интересен этот вопрос о типе данных. Если есть какие-то важные различия между двумя эти способами или если же нужно посимвольно определить массив только потому, что так надо, то я переделаю эту часть кода.

2020-11-25 10:53 UTC, alvls commented
Штрих-коды можете оставить.

2020-12-02 21:05 UTC, alser3217 commented
Успел!!!!!!! Для трёх видов сортировок (mergeSort, quickSort, countingSort) не реализовано совмещение имён файлов с отсортированными размерами, потому что в них используется разделение массива и создание новых, поэтому непонятно в какой момент, когда и как вставлять strcopy, чтобы было соответствие. Объясните пожалуйста, когда дойдёт дело до проверки.

2020-12-06 11:23 UTC, alser3217 commented
02.12 был сделан коммит необновлённого файла с кодом, в котором, как оказалось, не хватает порядка 100 строк. Я просто забыл скопировать обновлённый код в source.c task5. Заметил, когда понадобились скриншоты для отчёта.

2020-12-11 07:51 UTC, alvls commented
Работа   принята |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 2,0
Качество кода: | 2,0
Бонус: | 0,0
Штраф: | 1,0
__Итого:__ | 7,0

2020-12-19 20:58 UTC, alvls commented
Алексей, в задании 5 программа работает неверно. Я ввожу путь c:\temp\. выдает, что папка не содержит файлов, хотя это не так.

2020-12-19 21:56 UTC, alser3217 commented
Не знаю в чём может заключаться проблема, я проверил программу на путь,
который содержит один символ "\", преобразователь строк работает верно. Я
вводил строку как копированием, так и вручную, всё работает. Может быть, Вы
вводите лишний пробел после C:\temp ?
[image: image.png]

>

2020-12-20 16:01 UTC, alvls commented
Ваш метод stringEditor добавляет в конец строки 4 слеша вместо двух. Из-за этого получается некорректный путь. Исправьте.

2020-12-20 18:10 UTC, merged

2020-12-20 18:26 UTC, alvls commented
Теперь после ввода пути программа "задумывается", а потом падает.

2020-12-20 18:33 UTC, alser3217 commented
Я не знаю в чём проблема, потому что на моей системе после ввода пути
предлагается выбрать метод сортировки, скриншот я прикладывал ранее.

On Sun, 20 Dec 2020, 9:26 pm Alexander Sysoyev, <notifications@github.com>
wrote:

> Теперь после ввода пути программа "задумывается", а потом падает.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/alvls/mp1-2020-2/pull/54#issuecomment-748643151>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARAEZB6SZ6IHHVMABOWV3WLSVY6VTANCNFSM4TOKPOCA>
> .
>

2020-12-21 06:46 UTC, alvls commented
Запустите вашу программу на папке c:\windows\system32. У меня ваша программа падает после выбора сортировки (см. скрин).
![изображение](https://user-images.githubusercontent.com/5449780/102747399-469d2000-4371-11eb-894c-7b1c41cd9a85.png)

2020-12-21 07:40 UTC, alser3217 commented
Прикладываю запись с экрана. Папка Windows32 использовалось мною в качестве
папки для проверки скорости каждой сортировки в отчёте, тогда тоже всё
работало. Также я заметил, что Вы вводите путь с дополнительным слешем в
конце, хотя программа этого не предусматривает, так как при копировании в
проводнике путь выделяется без слеша на конце, скриншот тоже прикладываю.
https://drive.google.com/file/d/1nQLLhS6jCngC3fEKDEP4OySEg6Clg3Km/view?usp=sharing
[image: image.png]

пн, 21 дек. 2020 г. в 09:46, Alexander Sysoyev <notifications@github.com>:

> Запустите вашу программу на папке c:\windows\system32. У меня ваша
> программа падает после выбора сортировки (см. скрин).
> [image: изображение]
> <https://user-images.githubusercontent.com/5449780/102747399-469d2000-4371-11eb-894c-7b1c41cd9a85.png>
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/alvls/mp1-2020-2/pull/54#issuecomment-748796182>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARAEZB76K67FHYVOYZAUJM3SV3VM3ANCNFSM4TOKPOCA>
> .
>

2020-12-21 08:03 UTC, alvls commented on raschetnov_as/task5/Source.c
> +    slashes = (char*)malloc(sizeof(char) * 4);
В этом коде ошибка. Сначала вы выделяете память под slashes с помощью инициализации. Потом еще раз выделяете память через malloc.

2020-12-21 08:03 UTC, alvls commented on raschetnov_as/task5/Source.c
> +    char name[30];
Если длина имени будет больше 30 символов, то будет заход за память при копировании имени файла.

2020-12-21 08:06 UTC, alvls commented
Кроме замечаний выше. У меня ваша программа работает на сортировках с 3-й по 6-ю, на первых двух падает, на последней зависает.

2020-12-21 08:12 UTC, alser3217 commented
Последняя не реализована, вернее там есть код для неё, но она просто не
работает как должна, 1-ая и 2-ая должны работать. Пулл реквест закрыт, как
вносить правки ? Замечания я понял. Насчёт имени файла длиной в 30
символов. На путь тоже стоит ограничение в 256 символов, хотя он может
оказаться и длиннее. Я просто взял числа близкие к реальным длинам имён
файлов. Тут не угадаешь, а лишнюю память выделять не хочется.

>

2020-12-21 08:18 UTC, alvls commented
Я перепутал ваш пулл реквест с другим, поэтому сделал слияние.
Внесите правки, сделайте коммит, пуш на гитхаб. Затем создайте новый пулл реквест.
Чтобы не было проблем при копировании имен файлов, копируйте, используя strncpy

2020-12-21 08:31 UTC, alser3217 commented
Коммит сделан. Я пользовался функцией strcpy для копирования имён, но я не
знаю в каком месте нужно вставить эту функцию, где не совершается прямой
работы с исходным массивом размеров файлов, как например в
сортировке слиянием. Там массив делится на 2 и далее, и непонятно в каком
месте кода вставлять эту функцию.

>